import {dataCenter,rankingRows} from './data-center.mjs?v=20260927-4';
import {matchStatistics,teamHistory} from './statistics.mjs?v=20260927-4';
import {flagImage} from './flags.mjs?v=20260927-4';
import {icon} from './icons.mjs?v=20260927-4';
import {stateOf,chooseHero,filterMatches,fresh,dayKey,validateFeed,previewMatches,matchStatus} from './model.mjs?v=20260927-4';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>new Date(v.length===10?v+'T12:00:00+03:00':v).toLocaleDateString('tr-TR',{day:'numeric',month:'long',year:'numeric',timeZone:'Europe/Istanbul'});
const url=t=>t.archiveUrl||'/turnuvalar/'+t.id+'/';
const label=s=>({active:'Devam ediyor',upcoming:'Yaklaşan',archived:'Arşiv',cancelled:'İptal edildi'}[s]);
let catalog={tournaments:[],stories:[]}, feed={matches:[]}, old=[], teams=[], matchTab='today',calendarRange='all',calendarDay=null,feedError=false, history=null, teamArchives=[], stories=[], rankings={rows:[]}, dataFilters={league:'A',group:'all',round:'all',status:'all'}, rankingQuery='', archiveStage='all';
const empty=(title,text)=>`<div class="empty"><span class="symbol" aria-hidden="true">—</span><strong>${title}</strong><p>${text}</p></div>`;
const head=(title,link='',text='Tümünü gör')=>`<div class="heading"><h2>${title}</h2>${link?`<a href="${link}">${text} ↗</a>`:''}</div>`;
const art=t=>t.image|| (t.id==='2026-dunya-kupasi'?'/platform/images/gold-cup.png':t.id==='2028-avrupa-sampiyonasi'?'/platform/images/silver-cup.png':'/platform/images/national-hero.png');
const card=t=>`<a class="panel tourney photo-card" href="${url(t)}" style="--card-image:url('${art(t)}')"><small>${label(stateOf(t)).toLocaleUpperCase('tr-TR')}</small><div class="tourney-content"><h3>${esc(t.name)}</h3><p>${esc(t.edition)}<br>${esc(t.region)}</p><span class="btn">Turnuva Merkezi →</span></div></a>`;
function hero(){
 const h=chooseHero(catalog.tournaments,feed.matches);const t=h.item;
 let feature;
 if(h.type==='live')feature=`<span class="live-badge">CANLI</span><h2>${esc(t.home.name)}<br><span>${t.home.score??'–'} – ${t.away.score??'–'}</span><br>${esc(t.away.name)}</h2><a class="btn" href="/maclar/?gun=live">Maç Merkezine Git →</a>`;
 else if(t)feature=`<p>${h.type==='active'?'Devam Eden Turnuva':'Sıradaki Büyük Turnuva'}</p><h2><span>${esc(t.edition.split(' · ')[0])}</span><br>${esc(t.name)}</h2><small>${esc(t.region)}</small><div class="feature-dates">${date(t.startDate)}<br><span>${date(t.endDate)}</span></div><a class="btn" href="${url(t)}">Turnuva Merkezine Git →</a>`;
 else feature=`<p>Futbol Takvimi</p><h2>Bir sonraki<br><span>büyük buluşma.</span></h2><a class="btn" href="/takvim/">Takvimi Keşfet →</a>`;
 const quick=[['trophy','Tüm Turnuvalar','/turnuvalar/'],['shield','Milli Takımlar','/takimlar/'],['ball','Günün Maçları','/maclar/?gun=today'],['calendar','Futbol Takvimi','/takvim/'],['network','Maç Merkezi','/maclar/'],['chart','Veri Merkezi','/veri/'],['story','Hikâyeler','/hikayeler/'],['archive','Arşiv','/turnuvalar/arsiv/']];
 return `<section class="hero reference-hero"><div class="hero-copy"><h1>Millî heyecanın<br><em>her zamanı burada.</em></h1><p class="lead">Turnuvalar, takımlar, maçlar, istatistikler<br>ve unutulmaz hikâyeler tek yerde.</p><a class="btn" href="/maclar/?gun=today">Bugünün Maçlarını Gör →</a></div><aside class="hero-feature" style="--feature-image:url('${h.type==='upcoming'&&t?art(t):'/platform/images/gold-cup.png'}')">${feature}</aside></section><div class="quick" aria-label="Hızlı erişim">${quick.map(([i,name,path])=>`<a href="${path}">${icon(i)}<span>${name}</span></a>`).join('')}</div>`;
}
function matchRows(list){return list.map(m=>{const status=matchStatus(m);return `<article class="match-row"><div><small>${esc(status)}</small><small>${date(m.kickoff)}</small>${m.datePrecision==='day'?'':`<time>${new Date(m.kickoff).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'})}</time>`}</div><strong class="match-team">${flagImage(m.home.code)}${esc(teams.find(t=>t.code===m.home.code)?.name||({'Russia':'Rusya'}[m.home.name])||m.home.name)}</strong><b class="score">${['finished','live'].includes(m.status)?`${m.home.score??'–'} : ${m.away.score??'–'}`:'–'}${m.home.pen!=null&&m.away.pen!=null?`<small class="penalty-score">Pen. ${m.home.pen}–${m.away.pen}</small>`:''}</b><strong class="away match-team">${flagImage(m.away.code)}${esc(teams.find(t=>t.code===m.away.code)?.name||({'Russia':'Rusya'}[m.away.name])||m.away.name)}</strong>${m.sourceUrl&&/^https:\/\/www\.uefa\.com\//.test(m.sourceUrl)?`<a class="result-source" href="${esc(m.sourceUrl)}" target="_blank" rel="noopener noreferrer">UEFA · Sonuç kaynağı ↗</a>`:''}</article>`;}).join('');}
function matchBody(){const list=filterMatches(feed.matches,matchTab);return list.length?matchRows(list):empty(feedError?'Maç verisine ulaşılamadı':matchTab==='live'?'Doğrulanmış canlı maç verisi yok':'Bu gün için maç verisi henüz yok',feedError?'Bağlantı yeniden kurulunca maçlar burada görünecek.': 'Bu durum maç olmadığı anlamına gelmez. Doğrulanmış fikstür ve skorlar ulaştığında burada görünecek.');}
function matchSection(){return `<div class="panel"><div class="toolbar"><div class="tabs" aria-label="Maç günü">${[['live','Canlı'],['yesterday','Dün'],['today','Bugün'],['tomorrow','Yarın']].map(([id,n])=>`<button type="button" data-tab="${id}" aria-pressed="${matchTab===id}">${n}</button>`).join('')}</div><span class="status">Türkiye saati · ${feed.updatedAt?'Son kontrol: '+new Date(feed.updatedAt).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'}):'Güncel maç akışı bekleniyor'}</span></div><div id="matchBody">${matchBody()}</div>${feedError?'<div class="toolbar status" role="status">Skor servisine şu anda ulaşılamıyor. Son alınan veriler gösteriliyor.</div>':''}</div>`;}
function tournamentGroup(status){const list=catalog.tournaments.filter(t=>stateOf(t)===status);return list.length?`<div class="cards">${list.map(card).join('')}</div>`:empty(status==='active'?'Aktif turnuva kaydı yok':'Yeni turnuvalar bekleniyor','Doğrulanan organizasyonlar takvimde yer alacak.');}
function calendar(){const now=dayKey(new Date());const until=dayKey(new Date(Date.now()+(calendarRange==='all'?0:Number(calendarRange))*86400000));const events=catalog.tournaments.filter(t=>stateOf(t)!=='cancelled').flatMap(t=>[{date:t.startDate,title:t.name,kind:'Başlangıç',t},{date:t.endDate,title:t.name,kind:'Bitiş',t}]).filter(e=>e.date>=now&&(calendarRange==='all'||e.date<=until)).sort((a,b)=>a.date.localeCompare(b.date));return events.length?events.map(e=>`<a class="calendar-row" href="${url(e.t)}"><span class="calendar-day"><b>${Number(e.date.slice(8))}</b><small>${new Date(e.date+'T12:00:00Z').toLocaleDateString('tr-TR',{month:'short'})}</small></span><div><strong>${esc(e.title)}</strong><p>${e.kind} · ${date(e.date)}</p></div></a>`).join(''):empty('Bu aralıkta takvim kaydı yok','Diğer tarih aralıklarını inceleyebilirsin.');}
function teamCards(list){return `<div class="teams">${list.map(t=>`<a class="team-card" href="/takim/${t.slug}/"><span class="team-flag" aria-hidden="true">${flagImage(t.code)}</span><strong>${esc(t.name)}</strong><small>${esc(t.code)}</small></a>`).join('')}</div>`;}
const archives=()=>catalog.tournaments.filter(t=>stateOf(t)==='archived').sort((a,b)=>b.endDate.localeCompare(a.endDate));
const archiveTitle=t=>t.id==='2026-dunya-kupasi'?'2026 Dünya Kupası':t.name;
function archiveCard(t){return `<a class="archive-tile" href="${url(t)}" style="--archive-image:url('${art(t)}')"><div><h3>${esc(archiveTitle(t))}</h3><p>${esc(t.region)}</p><span class="archive-cta">Turnuva Arşivi →</span></div></a>`;}
function archivePromo(){return `<div class="archive-strip" aria-label="Tamamlanan turnuvalar">${archives().map(archiveCard).join('')}</div>`;}
const stageNames={'group-stage':'Grup Aşaması','round-of-16':'Son 16','quarterfinals':'Çeyrek Final','semifinals':'Yarı Final','3rd-place-match':'Üçüncülük','3rd-place':'Üçüncülük',final:'Final'};
function historyRows(){const list=(history?.matches||[]).filter(m=>archiveStage==='all'||m.stage===archiveStage);return matchRows(list);}
function historicalPage(t){
 if(!history)return page(archiveTitle(t),'Arşiv maçları yüklenemedi.','<a class="btn" href="'+url(t)+'">Yeniden dene</a>');
 const list=history.matches;const final=list.find(m=>m.stage==='final');const stages=[...new Set(list.map(m=>m.stage))];const count=new Set(list.flatMap(m=>[m.home.code,m.away.code])).size;
 const goals=list.reduce((sum,m)=>sum+(m.home.score??0)+(m.away.score??0),0);
 return `<div class="breadcrumb"><a href="/">Ana Sayfa</a> / <a href="/turnuvalar/">Turnuvalar</a> / <a href="/turnuvalar/arsiv/">Arşiv</a> / ${esc(archiveTitle(t))}</div><section class="historical-hero" style="--archive-image:url('${art(t)}')"><p class="eyebrow">TAMAMLANAN TURNUVA</p><h1>${esc(archiveTitle(t))}</h1><p>${esc(t.region)} · ${esc(t.edition)}</p><div class="champion-line">${flagImage(t.championCode)}<span>Şampiyon<strong>${esc(t.champion)}</strong></span></div></section><p class="intro">${esc(t.description)}</p><div class="stat-grid">${[[count,'Milli takım'],[list.length,'Maç kaydı'],[goals,'Gol · seri penaltıları hariç']].map(([n,l])=>`<div class="panel stat-box"><b>${n}</b><span>${l}</span></div>`).join('')}</div><section class="block framed">${head('Final')}<div class="panel">${final?matchRows([final]):empty('Final kaydı yok','')}</div></section><section class="block framed">${head('Eleme Turları')}<div class="history-bracket">${stages.filter(stage=>stage!=='group-stage').map(stage=>`<section><h3>${stageNames[stage]||esc(stage)}</h3>${list.filter(m=>m.stage===stage).map(m=>`<div class="bracket-result"><div>${flagImage(m.home.code)}<span>${esc(teams.find(t=>t.code===m.home.code)?.name||({'Russia':'Rusya'}[m.home.name])||m.home.name)}</span><b>${m.home.score}</b></div><div>${flagImage(m.away.code)}<span>${esc(teams.find(t=>t.code===m.away.code)?.name||({'Russia':'Rusya'}[m.away.name])||m.away.name)}</span><b>${m.away.score}</b></div>${m.home.pen!=null?`<small>Penaltılar: ${m.home.pen}–${m.away.pen}</small>`:''}</div>`).join('')}</section>`).join('')}</div></section><section class="block framed"><div class="heading"><h2>Tüm Maçlar</h2><select id="archiveStage" aria-label="Arşiv tur filtresi"><option value="all">Tüm turlar (${list.length})</option>${stages.map(stage=>`<option value="${stage}" ${archiveStage===stage?'selected':''}>${stageNames[stage]||esc(stage)}</option>`).join('')}</select></div><div id="archiveMatches" class="panel">${historyRows()}</div></section><p class="source">Maç verileri: ESPN · <a href="${esc(t.source)}" target="_blank" rel="noopener noreferrer">Resmî final kaynağı ↗</a></p>`;
}
const flag=side=>`<span class="flag" aria-hidden="true">${flagImage(side.code)}</span>`;
function compactMatches(list){return list.length?previewMatches(list).map(m=>`<a class="compact-match" href="/maclar/?gun=${dayKey(m.kickoff)===dayKey(new Date())?'today':'tomorrow'}"><span>${flag(m.home)}${esc(teams.find(t=>t.code===m.home.code)?.name||({'Russia':'Rusya'}[m.home.name])||m.home.name)}</span><b>${['finished','live'].includes(m.status)?`${m.home.score??'–'} : ${m.away.score??'–'}`:new Date(m.kickoff).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'})}</b><span>${flag(m.away)}${esc(teams.find(t=>t.code===m.away.code)?.name||({'Russia':'Rusya'}[m.away.name])||m.away.name)}</span><small>UEFA Uluslar Ligi · ${matchStatus(m)}</small></a>`).join(''):empty('Maç kaydı yok','Doğrulanmış maçlar burada görünecek.');}
function scoreboard(){const live=filterMatches(feed.matches,'live');const yesterday=filterMatches(feed.matches,'yesterday').filter(m=>m.status==='finished');const featured=(live.length?live:yesterday).find(m=>m.home.code==='TUR'||m.away.code==='TUR')||(live.length?live:yesterday)[0];
 return `<section class="block framed match-dashboard"><div><div class="heading"><h2>${live.length?'Canlı Maçlar':'Dünün Sonuçları'}</h2><a href="/maclar/?gun=yesterday">Dünün tüm maçları →</a></div>${featured?`<div class="featured-score"><p>${featured.status==='live'?'<span class="live-badge">CANLI</span>':date(featured.kickoff)+' · MAÇ SONUCU'}</p><div class="score-teams"><span>${flag(featured.home)}${esc(featured.home.name)}</span><b>${featured.home.score}–${featured.away.score}</b><span>${flag(featured.away)}${esc(featured.away.name)}</span></div><small>${esc(catalog.tournaments.find(t=>t.id===featured.tournamentId)?.name||'Milli maç')}</small><a class="btn" href="/maclar/?gun=${featured.status==='live'?'live':'yesterday'}">Maç Merkezi →</a></div>`:empty('Canlı maç verisi yok','Günün maçlarını yan tarafta görebilirsin.')}</div><div class="match-column">${head('Bugün · '+date(dayKey(new Date())),'/maclar/?gun=today','Tümü')}${compactMatches(filterMatches(feed.matches,'today'))}</div><div class="match-column">${head('Yarın · '+date(dayKey(new Date(Date.now()+86400000))),'/maclar/?gun=tomorrow','Tümü')}${compactMatches(filterMatches(feed.matches,'tomorrow'))}</div><p class="score-source">Son güncelleme: ${feed.updatedAt?date(feed.updatedAt)+' · '+new Date(feed.updatedAt).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'}):'—'}${feedError?' · Bağlantı kesildi; son alınan veriler.':Date.now()-Date.parse(feed.updatedAt)>900000?' · Veri güncellemesi gecikmiş.':''}</p></section>`;
}
function homeCalendar(){const days=[0,1,2,3,4,5,6].map(n=>{const d=new Date(Date.now()+n*86400000);return {key:dayKey(d),label:n===0?'Bugün':n===1?'Yarın':d.toLocaleDateString('tr-TR',{weekday:'short',timeZone:'Europe/Istanbul'}),date:d.toLocaleDateString('tr-TR',{day:'numeric',month:'short',timeZone:'Europe/Istanbul'})};});if(!days.some(d=>d.key===calendarDay))calendarDay=days[0].key;return `<section class="block framed">${head('Futbol Takvimi','/takvim/','Tüm takvim')}<div class="week-tabs">${days.map((d,i)=>`<button data-calendar-day="${d.key}" aria-pressed="${d.key===(calendarDay||days[0].key)}">${d.label}<small>${d.date}</small></button>`).join('')}</div><div id="homeCalendarMatches">${dayCards(calendarDay||days[0].key)}</div></section>`;}
function dayCards(day){const list=feed.matches.filter(m=>dayKey(m.kickoff)===day);return list.length?`<div class="day-cards">${list.map(m=>`<a href="/turnuvalar/${m.tournamentId}/"><span>${flag(m.home)}${esc(teams.find(t=>t.code===m.home.code)?.name||({'Russia':'Rusya'}[m.home.name])||m.home.name)}</span><b>${['live','finished'].includes(m.status)?`${m.home.score}–${m.away.score}`:new Date(m.kickoff).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'})}</b><span>${flag(m.away)}${esc(teams.find(t=>t.code===m.away.code)?.name||({'Russia':'Rusya'}[m.away.name])||m.away.name)}</span><small>${esc(catalog.tournaments.find(t=>t.id===m.tournamentId)?.name||'Milli maç')} · ${matchStatus(m)}</small></a>`).join('')}</div>`:empty('Bu gün için maç verisi yok','Takvim yeni veriler geldikçe güncellenir.');}
function homeData(){const results=feed.matches.filter(m=>m.status==='finished');const table=new Map();for(const m of results)for(const side of [m.home,m.away]){const row=table.get(side.name)||{name:side.name,goals:0,played:0};row.goals+=side.score;row.played++;table.set(side.name,row);}return `<div class="data-table"><div class="data-table-title">Son maçlarda takım golleri</div>${[...table.values()].sort((a,b)=>b.goals-a.goals).slice(0,5).map((t,i)=>`<div><span>${i+1}</span><strong>${esc(t.name)}</strong><small>${t.played} maç</small><b>${t.goals}</b></div>`).join('')}<p>Skor servisinden alınan ${results.length} tamamlanmış maç · Resmî sıralama değildir.</p></div>`;}
function countryArchives(code){
 const list=teamHistory([{id:'2026-dunya-kupasi',name:'2026 Dünya Kupası',endDate:'2026-07-19',matches:old.map(normalizeOld)},...teamArchives],code);
 return `<section class="block">${head('Son 5 Turnuva · Arşiv')}<p class="source">Katıldığı tamamlanmış turnuvalar · en yeniden eskiye</p>${list.map(t=>{const stats=matchStatistics(t.matches);let wins=0,draws=0,losses=0;for(const m of t.matches){const us=m.home.code===code?m.home:m.away,them=m.home.code===code?m.away:m.home;if(us.score>them.score)wins++;else if(us.score===them.score)draws++;else losses++;}return `<details class="panel team-history" open><summary><strong>${esc(t.name)}</strong><span>${stats.finished} maç · ${wins}G ${draws}B ${losses}M</span></summary>${matchRows(t.matches)}<p class="source">${t.source?'Kaynak: ESPN':'Kaynak: mevcut 2026 arşivi'} · G/B/M maç skoruna göre, seri penaltıları hariç.</p></details>`;}).join('')}${list.length<5?'<p class="source">Skor kaynağında bulunan '+list.length+' turnuva gösteriliyor. Eksik kayıtlar sonuç olarak varsayılmaz.</p>':''}</section>`;
}
const dataContext=()=>({catalog,feed,rankings,teams,flagImage,esc,date,head,empty,matchRows});
function currentStatistics(){return dataCenter(dataContext(),dataFilters,rankingQuery);}
function sectionCover(title,text,image){return `<section class="section-cover" style="--cover-image:url('${image}')"><div><p class="eyebrow">YILDIZ KUPASI</p><h2>${title}</h2><p>${text}</p></div></section>`;}
function currentStories(){
 const now=new Date(), stamp=feed.updatedAt||now.toISOString();
 const next=feed.matches.filter(m=>m.status==='scheduled'&&Date.parse(m.kickoff)>+now&&(m.home.code==='TUR'||m.away.code==='TUR')).sort((a,b)=>a.kickoff.localeCompare(b.kickoff))[0];
 const done=feed.matches.filter(m=>m.status==='finished').sort((a,b)=>b.kickoff.localeCompare(a.kickoff));
 const recentDay=done[0]?dayKey(done[0].kickoff):null, results=done.filter(m=>dayKey(m.kickoff)===recentDay);
 const list=[];
 if(next)list.push({slug:'turkiye-siradaki-mac',title:`${next.home.name}–${next.away.name}: sıradaki millî randevu`,tag:'GÜNCEL · MAÇ ÖNÜ',summary:`${date(next.kickoff)}, Türkiye saatiyle ${new Date(next.kickoff).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'})}. Millî takımın sıradaki karşılaşması.`,image:'/platform/images/national-hero.png',publishedAt:stamp,author:'Skor verilerinden otomatik özet',archiveUrl:'/takim/turkiye/',paragraphs:[`Millî takımın sıradaki maçı ${next.home.name} ile ${next.away.name} arasında. Karşılaşma ${date(next.kickoff)} tarihinde, Türkiye saatiyle ${new Date(next.kickoff).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'})} için planlanmış durumda.`,`Bu sayfa skor servisindeki fikstürü izler. Başlama saati veya maç durumu değiştiğinde metin de güncellenir. Kadro ve sakatlık bilgileri bu özetin kapsamına dahil değildir.`,`Millî takım sayfasında güncel sonuçları ve gelecek maçları birlikte inceleyebilirsin.`]});
 if(results.length){const goals=results.reduce((sum,m)=>sum+m.home.score+m.away.score,0);list.push({slug:'milli-futbolda-son-mac-gunu',title:`${date(recentDay)}: millî futbolda günün özeti`,tag:'GÜNCEL · SONUÇ DOSYASI',summary:`${results.length} tamamlanan maç, ${goals} gol. Son maç gününün skorlarına toplu bakış.`,image:'/platform/images/silver-cup.png',publishedAt:stamp,author:'Skor verilerinden otomatik özet',archiveUrl:'/maclar/?gun=yesterday',paragraphs:[`${date(recentDay)} tarihinde skor akışına yansıyan ${results.length} tamamlanmış maçta toplam ${goals} gol kaydedildi. Seri penaltıları gol toplamına dahil değildir.`,...results.map(m=>`${m.home.name} ${m.home.score}–${m.away.score} ${m.away.name}.`),'Bu özet tamamlanmış maç kayıtlarından otomatik oluşturulur. Skor düzeltmeleri geldiğinde içerik güncellenir; maçların oyununa ilişkin yorum veya doğrulanmamış haber içermez.']});}
 if(next&&list[0]){
  const recent=code=>feed.matches.filter(m=>m.status==='finished'&&(m.home.code===code||m.away.code===code)).sort((a,b)=>b.kickoff.localeCompare(a.kickoff))[0];
  const homeLast=recent(next.home.code),awayLast=recent(next.away.code);
  const group=next.group?.replace('Group ','')||'';
  const following=feed.matches.filter(m=>m.status==='scheduled'&&Date.parse(m.kickoff)>Date.parse(next.kickoff)&&(m.home.code==='TUR'||m.away.code==='TUR')).sort((a,b)=>a.kickoff.localeCompare(b.kickoff)).slice(0,3);
  list[0].sections=[{heading:'Maçın çerçevesi',paragraphs:[`Karşılaşma ${catalog.tournaments.find(t=>t.id===next.tournamentId)?.name||'milli takım turnuvası'} takviminde${group?' '+group+' grubunda':''} yer alıyor. Bu dosyada maçın zamanı, iki takımın son sonuçları ve Türkiye’nin takip eden programı birlikte ele alınıyor. Bilgiler maç akışı değiştikçe yenileniyor; maç başlamadan bir sonuç veya skor tahmini üretilmiyor.`]},{heading:'İki takım son maçında ne yaptı?',paragraphs:[homeLast?`${next.home.name} için akışta bulunan son tamamlanmış karşılaşma ${date(homeLast.kickoff)} tarihindeki ${homeLast.home.name}–${homeLast.away.name} maçı. Sonuç ${homeLast.home.score}–${homeLast.away.score}.`:'Ev sahibi takım için güncel sonuç kaydı henüz bulunmuyor.',awayLast?`${next.away.name} ise son tamamlanmış kayıtta ${date(awayLast.kickoff)} günü ${awayLast.home.name}–${awayLast.away.name} karşılaşmasında yer aldı. Bu maç ${awayLast.home.score}–${awayLast.away.score} sona erdi.`:'Deplasman takımı için güncel sonuç kaydı henüz bulunmuyor.','Bir önceki maçın sonucu, sıradaki karşılaşmanın sonucunu tek başına belirlemez. Buradaki veriler form değerlendirmesinin başlangıç noktasıdır; oyuncu performansı, sakatlık veya teknik tercihler hakkında doğrulanmamış çıkarımlar içermez.']},{heading:'Gruptaki tabloyu nasıl okumalı?',paragraphs:['Veri Merkezi’nde ilgili ligi ve grubu seçerek tamamlanan maç sayısını, galibiyetleri, beraberlikleri, atılan ve yenilen golleri görebilirsin. Puan özeti yalnızca bitmiş karşılaşmalardan hesaplanır; canlı maçın ara skoru kesin sonuç olarak tabloya eklenmez.','Maç haftası filtresi, aynı dönemde oynanan diğer grup karşılaşmalarını bir araya getirir. Böylece bir takımın sonucunu, rakiplerinin o haftaki programıyla birlikte incelemek mümkün olur. Puan eşitliklerinde resmî sıralama için turnuvanın ikili averaj kuralları ayrıca dikkate alınmalıdır.']},{heading:'Bu maçtan sonra Türkiye’nin programı',paragraphs:following.length?following.map(m=>`${date(m.kickoff)}: ${m.home.name}–${m.away.name}. Planlanan saat ${new Date(m.kickoff).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'})}, Türkiye saati.`):['Takip eden fikstür henüz kaynağa eklenmedi. Yeni maçlar doğrulandığında burada görünecek.']},{heading:'Takip rehberi',paragraphs:['Karşılaşma başladığında Maç Merkezi üzerinden gelen skor ve durum bilgileri izlenebilir. Başlama saati geçmiş olsa bile servis henüz canlı durum bildirmemişse, maç otomatik olarak başlamış kabul edilmez. Güncelleme gecikirse son doğrulanan bilgi korunur.','Bu dosyanın üstündeki tarih, verinin son kontrol edildiği zamanı gösterir. Resmî fikstür değişiklikleri veri kaynağına yansıdığında hem maç kartı hem de bu dosyanın program bölümü yenilenir.']}];
 }
 return [...list,...stories];
}
function storyCards(limit=100){return `<div class="story-grid">${currentStories().slice(0,limit).map(s=>`<a class="story-card" href="/hikayeler/${s.slug}/"><img src="${s.image}" alt="" loading="lazy"><div><small>${esc(s.tag)}</small><h3>${esc(s.title)}</h3><p>${esc(s.summary)}</p><p class="source">${date(s.publishedAt)}</p><span>Hikâyeyi oku →</span></div></a>`).join('')}</div>`;}
function storyPage(s){return page(s.title,s.summary,`<article class="story-article"><img class="story-cover" src="${s.image}" alt="Turnuva atmosferini yansıtan temsili illüstrasyon"><p class="source">${esc(s.author)} · ${date(s.publishedAt)} · ${esc(s.tag)}</p>${s.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}${(s.sections||[]).map(section=>`<section><h2>${esc(section.heading)}</h2>${section.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}</section>`).join('')}<a class="btn" href="${s.archiveUrl}">Maç kayıtları ve kaynaklar →</a><p class="source">Kaynak: ESPN maç ve fikstür kayıtları. Görsel temsili illüstrasyondur.</p></article>`);}
function home(){return hero()+scoreboard()+`<div class="tournament-columns"><section class="block framed">${head('Devam Eden Turnuvalar','/turnuvalar/')}${tournamentGroup('active')}</section><section class="block framed">${head('Yaklaşan Turnuvalar','/turnuvalar/')}${tournamentGroup('upcoming')}</section></div>`+homeCalendar()+`<section class="block framed">${head('Milli Takımlar','/takimlar/')}${teamCards(['TUR','ARG','FRA','ENG','BRA','GER','ESP','POR','NED'].map(code=>teams.find(t=>t.code===code)).filter(Boolean))}</section><div class="editorial-columns"><section class="block framed">${head('Öne Çıkan Hikâyeler','/hikayeler/')}${storyCards(2)}</section><section class="block framed">${head('Veri Merkezi','/veri/')}${homeData()}</section></div><section class="block framed">${head('Arşiv','/turnuvalar/arsiv/','Tüm arşiv')}${archivePromo()}</section><p class="illustration-note">Görseller temsili illüstrasyonlardır.</p>`;}
function page(title,desc,body){return `<div class="breadcrumb"><a href="/">Ana Sayfa</a> / ${esc(title)}</div><h1 class="page-title">${esc(title)}</h1><p class="intro">${desc}</p>${body}`;}
function render(){const path=location.pathname.replace(/\/$/,'')||'/';let html,title;
if(path==='/'){html=home();title='Milli Futbolun Buluşma Noktası';}
else if(path==='/maclar'){title='Maç Merkezi';html=page(title,'Dün, bugün, yarın ve canlı maçlar. Tüm saatler Türkiye saatine göredir.',`<section class="block">${matchSection()}</section>`);}
else if(path==='/turnuvalar'){title='Turnuvalar';html=page(title,'Milli futbolun devam eden ve yaklaşan organizasyonları.',`<section class="block">${head('Devam Eden')}${tournamentGroup('active')}</section><section class="block">${head('Yaklaşan')}${tournamentGroup('upcoming')}</section><section class="block">${archivePromo()}</section>`);}
else if(path==='/turnuvalar/arsiv'){title='Turnuva Arşivi';html=page(title,'Tamamlanan turnuvalar, kalıcı maç kayıtları ve finale giden yollar.',`<section class="block archive-grid">${archives().map(archiveCard).join('')}</section>`);}
else if(path.startsWith('/turnuvalar/arsiv/')){const t=catalog.tournaments.find(t=>t.archiveUrl?.replace(/\/$/,'')===path);if(t){title=archiveTitle(t);html=historicalPage(t);}}
else if(path==='/takvim'){title='Futbol Takvimi';html=page(title,'Doğrulanmış turnuva başlangıç ve bitiş tarihleri.',`<section class="block panel"><div class="toolbar"><div class="tabs" aria-label="Takvim aralığı">${[['7','7 gün'],['30','30 gün'],['all','Tüm takvim']].map(([id,n])=>`<button data-range="${id}" aria-pressed="${calendarRange===id}">${n}</button>`).join('')}</div></div><div id="calendarBody">${calendar()}</div></section>`);}
else if(path==='/takimlar'){title='Milli Takımlar';html=page(title,'2026 arşivindeki milli takımlar. Takımların maç kayıtlarını keşfet.',`<section class="block"><div class="heading"><h2>Takımları keşfet</h2><input class="search" id="teamSearch" type="search" placeholder="Takım ara…" aria-label="Milli takım ara"></div><div id="teamResults">${teamCards(teams)}</div></section>`);}
else if(path.startsWith('/takim/')){const t=teams.find(t=>path==='/takim/'+t.slug);if(t){title=t.name;const ms=old.filter(m=>m.home.code===t.code||m.away.code===t.code);html=page(t.name,'Milli takım merkezi',`<section class="country-cover" aria-label="${esc(t.name)} milli takım kapak görseli"><div class="country-cover-copy"><p class="eyebrow">MİLLİ TAKIM ATLASI</p><h2>${esc(t.name)}</h2><p>Bir ülke. Bir forma.<br>Birlikte yazılan futbol hikâyesi.</p><span>${esc(t.code)}</span></div><div class="country-emblem" aria-hidden="true">${flagImage(t.code)}</div><div class="pitch-lines" aria-hidden="true"></div></section><div class="notice">${rankings.rows.find(r=>r.code===t.code)?'FIFA dünya sıralaması: '+rankings.rows.find(r=>r.code===t.code).rank+' · Resmî yayın: '+date(rankings.publicationDate):'Resmî sıralama kaydı bekleniyor.'}</div><section class="block">${head('Güncel Maçlar','/maclar/')}<div class="panel">${matchRows(feed.matches.filter(m=>m.home.code===t.code||m.away.code===t.code))||empty('Güncel maç kaydı yok','Skor servisinden gelen maçlar burada gösterilir.')}</div></section>${countryArchives(t.code)}`);}}
else if(path==='/veri'){title='Veri Merkezi';html=page(title,'Güncel maç sonuçlarından otomatik hesaplanan turnuva istatistikleri.',`${sectionCover('Oyunun sayılarla hikâyesi','Sonuçlar, fikstür ve her golün bıraktığı iz.','/platform/images/silver-cup.png')}<p class="source">Son güncelleme: ${feed.updatedAt?date(feed.updatedAt)+' '+new Date(feed.updatedAt).toLocaleTimeString('tr-TR',{timeZone:'Europe/Istanbul',hour:'2-digit',minute:'2-digit'}):'Bekleniyor'}. Sayılar mevcut skor akışını kapsar; tam sezon toplamı değildir.</p>${currentStatistics()}<section class="block">${head('Geçmiş Turnuvalar','/turnuvalar/arsiv/','Arşivi aç')}${archivePromo()}</section>`);}
else if(path==='/hikayeler'){title='Hikâyeler';html=page(title,'Milli futbolun unutulmaz maçları, turnuva yolculukları ve arşiv dosyaları.',sectionCover('Skorun ötesinde','Final geceleri, milli heyecan ve unutulmaz yolculuklar.','/platform/images/national-hero.png')+storyCards());}
else if(path.startsWith('/hikayeler/')){const story=currentStories().find(s=>path==='/hikayeler/'+s.slug);if(story){title=story.title;html=storyPage(story);}}
else if(path.startsWith('/turnuvalar/')){const t=catalog.tournaments.find(t=>path==='/turnuvalar/'+t.id);if(t){title=t.name;const list=feed.matches.filter(m=>m.tournamentId===t.id);html=page(t.name,esc(t.edition)+' · '+esc(t.region),`<section class="block"><span class="tag">${label(stateOf(t))}</span><p>${esc(t.description)}</p><div class="stat-grid"><div class="panel stat-box"><span>Başlangıç</span><h3>${date(t.startDate)}</h3></div><div class="panel stat-box"><span>Bitiş</span><h3>${date(t.endDate)}</h3></div></div><p class="source"><a href="${esc(t.source)}" target="_blank" rel="noopener noreferrer">Takvim kaynağı ↗</a> · Kontrol: ${date(catalog.verifiedAt)}</p></section><section class="block">${head('Maçlar')}<div class="panel">${list.length?matchRows(list):empty('Fikstür verisi bekleniyor','Doğrulanmış maçlar ve sonuçlar ulaştığında burada görünecek.')}</div></section>`);}}
if(!html){title='Sayfa bulunamadı';html=page(title,'Aradığın sayfa mevcut değil.','<a class="btn" href="/">Ana sayfaya dön</a>');}
$('#content').innerHTML=html;document.title=title+' | Yıldız Kupası';bind();}
function normalizeOld(m){return {...m,kickoff:m.date,home:{...m.home,name:teams.find(t=>t.code===m.home.code)?.name||m.home.code},away:{...m.away,name:teams.find(t=>t.code===m.away.code)?.name||m.away.code}};}
function bind(){if($('#rankingSearch'))$('#rankingSearch').oninput=e=>{rankingQuery=e.target.value;$('#rankingRows').innerHTML=rankingRows(dataContext(),rankingQuery);};for(const [id,key] of [['dataLeague','league'],['dataGroup','group'],['dataRound','round'],['dataStatus','status']])if($('#'+id))$('#'+id).onchange=e=>{dataFilters[key]=e.target.value;if(key==='league')dataFilters.group='all';render();};if($('#archiveStage'))$('#archiveStage').onchange=e=>{archiveStage=e.target.value;$('#archiveMatches').innerHTML=historyRows();};document.querySelectorAll('[data-calendar-day]').forEach(b=>b.onclick=()=>{calendarDay=b.dataset.calendarDay;document.querySelectorAll('[data-calendar-day]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('#homeCalendarMatches').innerHTML=dayCards(b.dataset.calendarDay);});document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{matchTab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('#matchBody').innerHTML=matchBody();});document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{calendarRange=b.dataset.range;document.querySelectorAll('[data-range]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('#calendarBody').innerHTML=calendar();});if($('#teamSearch'))$('#teamSearch').oninput=e=>{const list=teams.filter(t=>t.name.toLocaleLowerCase('tr-TR').includes(e.target.value.toLocaleLowerCase('tr-TR')));$('#teamResults').innerHTML=list.length?teamCards(list):empty('Takım bulunamadı','Farklı bir adla tekrar ara.');};}
async function get(path){const r=await fetch(path,{cache:'no-store',signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error('Veri alınamadı');return r.json();}
let refreshing=false;
async function refresh(initial=false){
 if(refreshing)return;refreshing=true;
 try{
  catalog=await get('/platform/catalog.json');
  if(initial)stories=await get('/platform/stories.json');
  rankings=await get('/platform/rankings.json').catch(()=>rankings);
  let failed=false;const snapshot=await get('/platform/current.json?v='+Math.floor(Date.now()/60000)).then(validateFeed).catch(()=>{failed=true;return feed;});
  if(initial){const [a,t]=await Promise.all([get('/turnuvalar/arsiv/2026-dunya-kupasi/data/matches.json'),get('/platform/teams.json')]);old=a.matches;teams=t;if(location.pathname.startsWith('/takim/'))teamArchives=(await get('/platform/team-history.json').catch(()=>({tournaments:[]}))).tournaments;const target=catalog.tournaments.find(t=>t.archiveUrl===location.pathname&&t.archiveData);if(target)history=await get(target.archiveData).then(validateFeed);}
  feed=snapshot;feedError=failed||!snapshot.source;
  if(initial){const requested=new URLSearchParams(location.search).get('gun');if(['live','yesterday','today','tomorrow'].includes(requested))matchTab=requested;}
  $('#today').textContent=new Date().toLocaleDateString('tr-TR',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'Europe/Istanbul'});
  if(document.activeElement?.tagName!=='INPUT')render();
 }catch{
  if(initial){$('#content').innerHTML=page('Veriler yüklenemedi','Lütfen bağlantını kontrol edip yeniden dene.','<button id="retry">Yeniden dene</button>');$('#retry').onclick=()=>refresh(true);}
  else{feedError=true;render();}
 }finally{refreshing=false;}
}
$('#menu').onclick=()=>{const isOpen=$('#nav').classList.toggle('open');$('#menu').setAttribute('aria-expanded',isOpen);};
$('#today').textContent=new Date().toLocaleDateString('tr-TR',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'Europe/Istanbul'});
document.querySelectorAll('#nav a').forEach(a=>{if(a.pathname===location.pathname)a.setAttribute('aria-current','page');});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});
window.addEventListener('online',()=>refresh());
refresh(true);setInterval(()=>{if(!document.hidden)refresh();},60000);
