import {translations} from './score-provider.mjs';
import {groupCode,roundOf,competitionMatches,groupTable} from './competition.mjs';
import {matchStatistics} from './statistics.mjs';
export function rankingRows({rankings,teams,flagImage,esc},query=''){
 const rows=(rankings.rows||[]).filter(r=>(teams.find(t=>t.code===r.code)?.name||translations[r.name]||r.name).toLocaleLowerCase('tr-TR').includes(query.toLocaleLowerCase('tr-TR')));
 return `<div class="table-scroll ranking-scroll"><table class="football-table"><thead><tr><th>Sıra</th><th>Ülke</th><th>Puan</th><th>Değişim</th><th>Konfederasyon</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.rank}</td><td>${flagImage(r.code)} ${esc(teams.find(t=>t.code===r.code)?.name||translations[r.name]||r.name)}</td><td>${r.points.toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2})}</td><td>${r.movement>0?'↑ '+r.movement:r.movement<0?'↓ '+Math.abs(r.movement):'—'}</td><td>${esc(r.confederation)}</td></tr>`).join('')}</tbody></table></div>`;
}
export function dataCenter(ctx,filters,query=''){
 const {catalog,feed,rankings,teams,flagImage,esc,date,head,empty,matchRows}=ctx;
 const t=catalog.tournaments.find(t=>t.scoreProvider);if(!t)return empty('Turnuva verisi bekleniyor','');
 const groups=[...new Set(feed.matches.map(groupCode).filter(Boolean))].filter(g=>filters.league==='all'||g.startsWith(filters.league)).sort();
 const list=competitionMatches(feed.matches,t,filters),stats=matchStatistics(list),full=competitionMatches(feed.matches,t,{league:filters.league,group:filters.group});
 const shownGroups=[...new Set(full.map(groupCode).filter(Boolean))].sort();
 return `<section class="block framed">${head(esc(t.name)+' · '+esc(t.edition))}<div class="competition-filters"><label>Lig<select id="dataLeague">${['all','A','B','C','D'].map(v=>`<option value="${v}" ${filters.league===v?'selected':''}>${v==='all'?'Tüm ligler':v+' Ligi'}</option>`).join('')}</select></label><label>Grup<select id="dataGroup"><option value="all">Tüm gruplar</option>${groups.map(g=>`<option ${filters.group===g?'selected':''}>${g}</option>`).join('')}</select></label><label>Maç haftası<select id="dataRound"><option value="all">Tüm haftalar</option>${(t.matchdays||[]).map((d,i)=>`<option value="${i+1}" ${filters.round==String(i+1)?'selected':''}>${i+1}. hafta</option>`).join('')}</select></label><label>Maç durumu<select id="dataStatus">${[['all','Tüm maçlar'],['finished','Sonuçlar'],['scheduled','Oynanacak'],['live','Canlı']].map(([v,l])=>`<option value="${v}" ${filters.status===v?'selected':''}>${l}</option>`).join('')}</select></label></div>
 <div class="stat-grid">${[[stats.finished,'Tamamlanan'],[stats.live,'Canlı'],[stats.scheduled,'Oynanacak'],[stats.goals,'Gol · tamamlanan maçlar'],[stats.average.replace('.',','),'Gol ortalaması'],[stats.total,'Seçili maç']].map(([n,l])=>`<div class="panel stat-box"><b>${n}</b><span>${l}</span></div>`).join('')}</div>
 <details class="standings-panel" open><summary>Grup puan özetleri</summary><div class="group-tables">${shownGroups.map(g=>`<div><h3>Grup ${g}</h3><div class="table-scroll"><table class="football-table"><thead><tr><th>Takım</th><th>O</th><th>G</th><th>B</th><th>M</th><th>AG</th><th>YG</th><th>Av.</th><th>P</th></tr></thead><tbody>${groupTable(full.filter(m=>groupCode(m)===g)).map(r=>`<tr><td>${flagImage(r.code)} ${esc(r.name)}</td><td>${r.played}</td><td>${r.won}</td><td>${r.drawn}</td><td>${r.lost}</td><td>${r.for}</td><td>${r.against}</td><td>${r.for-r.against}</td><td><b>${r.points}</b></td></tr>`).join('')}</tbody></table></div></div>`).join('')}</div><p class="source">Tamamlanan grup maçlarından hesaplanır. Eşit puanlarda genel averaj kullanılır; resmî ikili averaj sırası değildir.</p></details>
 <h3>Fikstür ve Sonuçlar · ${list.length} maç</h3>${list.length?(t.matchdays||[]).map((d,i)=>{const matches=list.filter(m=>roundOf(m,t)===i+1);return matches.length?`<section class="fixture-round"><h4>${i+1}. Maç Haftası · ${date(d.from)} – ${date(d.to)}</h4><div class="panel">${matchRows(matches)}</div></section>`:'';}).join(''):empty('Bu filtrelerde maç yok','Diğer karşılaşmalar için filtreleri değiştir.')}</section>
 <section class="block framed" id="dunya-siralamasi">${head('FIFA Dünya Sıralaması')}<p class="source">Erkek milli takımlar · Resmî yayın: ${rankings.publicationDate?date(rankings.publicationDate):'Veri bekleniyor'} · Son kontrol: ${rankings.checkedAt?date(rankings.checkedAt):'—'}</p>${rankings.nextUpdateDate?`<p class="source">Sıradaki resmî güncelleme: ${date(rankings.nextUpdateDate)}.</p>`:''}<input class="search" id="rankingSearch" aria-label="Dünya sıralamasında ülke ara" placeholder="Ülke ara…" value="${esc(query)}"><div id="rankingRows">${rankingRows(ctx,query)}</div><details class="data-provenance"><summary>Veri hakkında</summary><p>Resmî FIFA yayını her gün kontrol edilir. Yeni liste yayımlandığında otomatik alınır; erişim sorunu olursa son doğrulanan liste korunur.</p><a href="https://inside.fifa.com/fifa-rankings/world-ranking/men" target="_blank" rel="noopener">Resmî sıralamayı doğrula ↗</a></details></section>`;
}
